---
- locale_gen:
    name: "{{ db.locale }}"

- name: Add PostgreSQL repo
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    filename: postgresql

- name: Import the repository signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: ACCC4CF8

- name: Install postgresql
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - postgresql-9.6
    - libpq-dev
    - python3-psycopg2

- name: Create postgresql user
  postgresql_user:
    name: "{{ db.user }}"
  become_user: postgres

- name: Creare postgresql db
  postgresql_db:
    name: "{{ db.name }}"
    owner: "{{ db.user }}"
    encoding: UTF-8
    lc_collate: "{{ db.locale }}"
    lc_ctype: "{{ db.locale }}"
    template: template0
  become_user: postgres
